# This is a basic workflow to help you get started with Actions

name: Wildfire data scraper

# Controls when the workflow will run
on:
  # schedule:
   # - cron: "0 2 * * *" #2am daily. https://crontab.guru/examples.html

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# required for python/github bug. may not be req'd
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true 

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Nodejs ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        # github sets this for you
        with:
          node-version: ${{ matrix.node-version }}
          # repo-token: ${{ secrets.GITHUB_TOKEN }}

      # Install needed libs
      - name: Install dependencies
        run: |
          npm ci

      # Runs our python script
      - name: Get latest wildire data from B.C. gov't
        run: |
          node index.js

      # Commits files
      - name: Commit results
        run: |
          git config --global user.email "action@hgithub.com"
          git config --global user.name "Github action"
          git commit -am "ran data update script"
          
      # Push changes
      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # github sets this for you
        run: |
          git push

  
