# This is a basic workflow to help you get started with Actions

name: Wildfire data scraper

# Controls when the workflow will run
on:
  schedule:
  # - cron: "0 9 * * *" #run at 2am daily (pst). https://crontab.guru/examples.html
  - cron: "0 */3 * * *" # run every three hours

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [20.x]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      # Install needed libs
      - name: Install dependencies
        run: |
          npm ci

      # Runs scraper
      - name: Get latest wildire data from B.C. gov't
        run: |
          node index.js

      # Commit changes
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          # Defaults to "Apply automatic changes"
          commit_message: Updated with latest fire data

  
